# Generated by Django 4.2 on 2025-02-22 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_optcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optcode',
            name='code',
            field=models.CharField(default=655099, max_length=6),
        ),
        migrations.AlterField(
            model_name='optcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt', to=settings.AUTH_USER_MODEL),
        ),
    ]
