# Generated by Django 4.2 on 2025-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_optcode_code_alter_optcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optcode',
            name='code',
            field=models.CharField(default=230400, max_length=6),
        ),
    ]
