# Generated by Django 4.2 on 2025-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_optcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optcode',
            name='code',
            field=models.CharField(default=786665, max_length=6),
        ),
    ]
