# Generated by Django 4.2 on 2025-03-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_optcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optcode',
            name='code',
            field=models.CharField(default=217377, max_length=6),
        ),
    ]
