# Generated by Django 4.2 on 2025-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_subject_need_score_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='can_read',
            field=models.BooleanField(default=False),
        ),
    ]
