# Generated by Django 4.2 on 2025-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level_user',
            field=models.IntegerField(default=1),
        ),
    ]
