# Generated by Django 4.2 on 2025-02-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcode',
            name='user_code',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
