# Generated by Django 4.2 on 2025-02-03 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codes', '0002_subcode_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcode',
            name='user_code',
        ),
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_code', models.FileField(upload_to='')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='codes.subcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
