# Generated by Django 4.2 on 2025-02-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_remove_subcode_user_remove_subcode_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeruser',
            name='sub_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='codes.subcode'),
        ),
    ]
