# Generated by Django 4.2 on 2025-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_alter_answeruser_sub_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
