# Generated by Django 4.2 on 2025-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_answeruser_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='score',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
