# Generated by Django 4.2 on 2025-03-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_answeruser_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeruser',
            name='score',
        ),
        migrations.AddField(
            model_name='subcode',
            name='score',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
